version: '3'
services:
  raytracer:
    build:
      context: .
      dockerfile: ./deployment/raytracer_cli/Dockerfile
    volumes:
      - "${VOLUME}:/var/raytracer"
    environment:
      - "VOLUME=${VOLUME}"
      - "SCENARIO=${SCENARIO}"
      - "OUTPUT=/var/raytracer/${OUTPUT}"
    command:
      sh /run.sh
    restart: "no"
